version: '3'
services:

  flask:
    build: .
    hostname: flask
    container_name: users
    image: users:latest
    restart: unless-stopped
    environment:
      TEAM_NAME: CC_1395_1632
      MONGODB_DATABASE: mymongodb
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
      MONGODB_HOSTNAME: mongodb
    ports:
      - "80:80"
    volumes:
      - appdata:/var/www/users/
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mymongodb
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro


volumes:
  appdata:
    driver: local
